# Generated by Django 4.1.6 on 2023-02-23 20:11

from django.db import migrations, models
import uploadapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'images"."account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumbnail_sizes', models.JSONField(default=list)),
                ('has_image_link', models.BooleanField()),
                ('has_expiring_links', models.BooleanField()),
            ],
            options={
                'db_table': 'images"."accounttier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.ImageField(upload_to=uploadapi.models.upload_to)),
            ],
            options={
                'db_table': 'images"."image',
                'managed': False,
            },
        ),
    ]
